# Site wide configuration

title:            
locale:           en_US
url: https://cpankajr.github.io
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Pankaj Chauhan
  avatar: bio-photo-1.jpg
  position: Under-Graduate Student
  school: St. Francis Institute of Technology
  place: Mumbai, IN.
  bio: "Under-Graduate student<br/>EXTC Department&#13;&#10;St. Francis Institute of Technology&#13;&#10;Mumbai"
  email: cpankajr@gmail.com
  disqus-shortname:
  twitter: cpankajr #username
  facebook: cpankajr #username
  google:
    plus: 114354609186386046762 #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: cpankajr
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: cpankajr #username
  xing: #username
  instagram: cpankajr #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
